INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('John Doe', 90741, 38);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('James Smith', 313500, 50);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Tatyana Fitzpatrick', 385750, 19);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Michael Silva', 198500, 66);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Paul Byrd', 725000, 64);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Gloria Little', 237500, 59);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Bradley Greer', 132000, 41);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Dai Rios', 217500, 35);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Jeanette Caldwell', 345000, 30);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Yuri Berry', 54781, 40);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Caesar Vance', 2145, 20);
INSERT INTO EMPLOYEE (NAME, SALARY, AGE) VALUES ('Doris Wilder', 98745, 30);

